#端口号 出错访问路径 项目访问路径 session失效时间 请求编码 最大线程数
server:
  port: 8082
  servlet:
    context-path: /
    session:
      timeout: 30m
  tomcat:
    uri-encoding: utf-8
    max-threads: 500
#多配置文件
spring:
  profiles:
    active: jdbc,redis
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 400MB
      max-request-size: 4000MB
      resolve-lazily: false
netty:
  host: 127.0.0.1
  port: 8090
  bossThread: 2 #线程数
  workerThread: 2 #线程数
  keepalive: true #保持连接
  backlog: 150






